'use client'

import { Html, OrbitControls, Sparkles } from '@react-three/drei'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { bodyPins, latLonToVector3, type CelestialBody, type GazetteerPin } from '@/lib/gazetteer'

type SatelliteRecord = { noradId: number; name: string; line1: string; line2: string; type: 'active' | 'debris' | 'station' }
type SatellitePoint = { noradId: number; lat: number; lon: number; alt: number; x: number; y: number; z: number }
type SelectedSatellite = SatelliteRecord & SatellitePoint

const palette: Record<CelestialBody, string> = { Sun: '#f59e0b', Mercury: '#9ca3af', Venus: '#d6a86a', Earth: '#2563eb', Moon: '#b8c0cc', Mars: '#c2412d', Jupiter: '#c78d64', Saturn: '#d6b878', Uranus: '#67d6df', Neptune: '#3157ce' }
const size: Record<CelestialBody, number> = { Sun: 1.8, Mercury: 1.25, Venus: 1.48, Earth: 1.55, Moon: 1.05, Mars: 1.42, Jupiter: 2.1, Saturn: 1.95, Uranus: 1.7, Neptune: 1.68 }
const satelliteColors = { leo: new THREE.Color('#ec4899'), meo: new THREE.Color('#facc15'), geo: new THREE.Color('#22d3ee'), debris: new THREE.Color('#ef4444') }

function CameraRig({ body, locked }: { body: CelestialBody; locked: SelectedSatellite | null }) {
  const target = useRef(new THREE.Vector3())
  useFrame(({ camera }) => {
    const desired = locked ? new THREE.Vector3(locked.x / 9000, locked.z / 9000, locked.y / 9000).multiplyScalar(7) : new THREE.Vector3(0, 0, body === 'Sun' ? 7 : body === 'Jupiter' ? 6.8 : 5.8)
    camera.position.lerp(desired, 0.045)
    target.current.lerp(locked ? desired.clone().multiplyScalar(0.35) : new THREE.Vector3(), 0.06)
    camera.lookAt(target.current)
  })
  return null
}
function Rings({ body, radius }: { body: CelestialBody; radius: number }) { if (body !== 'Saturn' && body !== 'Uranus') return null; return <mesh rotation={[body === 'Uranus' ? Math.PI / 2 : 0.34, body === 'Uranus' ? 0.45 : 0, 0]} receiveShadow castShadow><ringGeometry args={[radius * 1.35, radius * 2.15, 96]} /><meshStandardMaterial color={body === 'Saturn' ? '#caa96c' : '#79cbd3'} transparent opacity={0.75} side={THREE.DoubleSide} roughness={0.65} /></mesh> }
function BodyMesh({ body }: { body: CelestialBody }) { const radius = size[body]; const material = useMemo(() => new THREE.MeshStandardMaterial({ color: palette[body], roughness: body === 'Sun' ? 0.2 : 0.72, emissive: body === 'Sun' ? '#f97316' : '#000', emissiveIntensity: body === 'Sun' ? 1.5 : 0 }), [body]); return <group><mesh castShadow receiveShadow><sphereGeometry args={[radius, 96, 96]} /><primitive object={material} attach="material" /></mesh><Rings body={body} radius={radius} />{body === 'Sun' && <><mesh scale={1.12}><sphereGeometry args={[radius, 64, 64]} /><meshBasicMaterial color="#fbbf24" transparent opacity={0.1} /></mesh><pointLight color="#fbbf24" intensity={18} distance={25} /></>}</group> }
function Marker({ pin, onSelect }: { pin: GazetteerPin; onSelect: (pin: GazetteerPin) => void }) { const p = latLonToVector3(pin.lat, pin.lon); return <group position={[p.x, p.y, p.z]}><mesh onClick={(event) => { event.stopPropagation(); onSelect(pin) }}><sphereGeometry args={[0.075, 16, 16]} /><meshBasicMaterial color="#facc15" /></mesh><Html distanceFactor={7} center><button className="gazetteer-marker" onClick={(event) => { event.stopPropagation(); onSelect(pin) }} aria-label={`Open ${pin.name} marker`}><span />{pin.name}</button></Html></group> }

function ConjunctionWarning({ first, second }: { first: SatellitePoint; second: SatellitePoint }) { const a = new THREE.Vector3(first.x / 9000, first.z / 9000, first.y / 9000); const b = new THREE.Vector3(second.x / 9000, second.z / 9000, second.y / 9000); const midpoint = a.clone().add(b).multiplyScalar(0.5); const distance = a.distanceTo(b); return <group><line><bufferGeometry><bufferAttribute attach="attributes-position" args={[new Float32Array([...a.toArray(), ...b.toArray()]), 3]} count={2} itemSize={3} /></bufferGeometry><lineDashedMaterial color="#ef4444" dashSize={0.08} gapSize={0.06} linewidth={2} /></line><mesh position={midpoint} scale={[Math.max(distance, 0.18) * 1.8, 0.12, 0.12]}><sphereGeometry args={[1, 24, 12]} /><meshBasicMaterial color="#ef4444" transparent opacity={0.16} /></mesh></group> }

function Orbiters({ records, onSelect, onReady }: { records: SatelliteRecord[]; onSelect: (satellite: SelectedSatellite) => void; onReady: (count: number) => void }) {
  const mesh = useRef<THREE.InstancedMesh>(null)
  const [points, setPoints] = useState<SatellitePoint[]>([])
  const [selected, setSelected] = useState<SelectedSatellite | null>(null)
  const workerRef = useRef<Worker | null>(null)
  const recordMap = useMemo(() => new Map(records.map((record) => [record.noradId, record])), [records])
  useEffect(() => { const worker = new Worker(new URL('../workers/satellite-propagator.worker.ts', import.meta.url)); workerRef.current = worker; worker.onmessage = (event: MessageEvent<{ type: string; count?: number; points?: SatellitePoint[] }>) => { if (event.data.type === 'ready') onReady(event.data.count ?? 0); if (event.data.type === 'positions') setPoints(event.data.points ?? []) }; worker.postMessage({ type: 'init', satellites: records }); const timer = window.setInterval(() => worker.postMessage({ type: 'tick', timestamp: Date.now() }), 1000); return () => { window.clearInterval(timer); worker.terminate() } }, [records, onReady])
  useEffect(() => { const object = mesh.current; if (!object) return; const temp = new THREE.Object3D(); points.forEach((point, index) => { temp.position.set(point.x / 9000, point.z / 9000, point.y / 9000); temp.scale.setScalar(0.035 + Math.max(0, Math.min(point.alt / 40000, 0.08))); temp.updateMatrix(); object.setMatrixAt(index, temp.matrix); const record = recordMap.get(point.noradId); const color = record?.type === 'debris' ? satelliteColors.debris : point.alt > 30000 ? satelliteColors.geo : point.alt > 2000 ? satelliteColors.meo : satelliteColors.leo; object.setColorAt(index, color) }); object.count = points.length; object.instanceMatrix.needsUpdate = true; if (object.instanceColor) object.instanceColor.needsUpdate = true }, [points, recordMap])
  const handleClick = useCallback((event: { instanceId?: number; stopPropagation: () => void }) => { event.stopPropagation(); const point = points[event.instanceId ?? -1]; const record = point && recordMap.get(point.noradId); if (point && record) { const next = { ...record, ...point }; setSelected(next); onSelect(next) } }, [points, recordMap, onSelect])
  const trajectory = useMemo(() => { if (!selected) return null; const curve = new THREE.EllipseCurve(0, 0, 3.2, 2.3, 0, Math.PI * 2, false, 0.4); return curve.getPoints(96).map((p) => new THREE.Vector3(p.x, p.y * 0.4, p.x * 0.3)) }, [selected])
  const debrisPair = useMemo(() => { const debris = points.filter((point) => recordMap.get(point.noradId)?.type === 'debris'); for (let i = 0; i < debris.length; i += 1) for (let j = i + 1; j < debris.length; j += 1) { const distanceKm = Math.hypot(debris[i].x - debris[j].x, debris[i].y - debris[j].y, debris[i].z - debris[j].z); if (distanceKm <= 10) return [debris[i], debris[j]] as const } return null }, [points, recordMap])
  return <>{records.length > 0 && <instancedMesh ref={mesh} args={[undefined, undefined, records.length]} onClick={handleClick}><sphereGeometry args={[1, 6, 6]} /><meshBasicMaterial vertexColors /></instancedMesh>}{trajectory && <line><bufferGeometry><bufferAttribute attach="attributes-position" args={[new Float32Array(trajectory.flatMap((p) => [p.x, p.y, p.z])), 3]} count={trajectory.length} itemSize={3} /></bufferGeometry><lineBasicMaterial color="#ec4899" transparent opacity={0.8} /></line>}{debrisPair && <ConjunctionWarning first={debrisPair[0]} second={debrisPair[1]} />}</>
}

function Scene({ body, records, onSelect, onReady }: { body: CelestialBody; records: SatelliteRecord[]; onSelect: (satellite: SelectedSatellite) => void; onReady: (count: number) => void }) { const [selectedPin, setSelectedPin] = useState<GazetteerPin | null>(null); const [selectedSatellite, setSelectedSatellite] = useState<SelectedSatellite | null>(null); const pins = bodyPins(body); return <><CameraRig body={body} locked={selectedSatellite} /><ambientLight intensity={body === 'Sun' ? 0.5 : 0.28} /><directionalLight position={[4, 3, 5]} intensity={body === 'Sun' ? 0.2 : 2.8} castShadow /><BodyMesh body={body} /><Orbiters records={records} onSelect={(satellite) => { setSelectedSatellite(satellite); onSelect(satellite) }} onReady={onReady} />{pins.map((pin) => <Marker key={pin.id} pin={pin} onSelect={setSelectedPin} />)}<Sparkles count={70} scale={14} size={1.2} speed={0.2} color="#9ccfff" />{selectedPin && <Html position={[0, -2.5, 0]} center><article className="gazetteer-card"><button className="gazetteer-close" onClick={() => setSelectedPin(null)} aria-label="Close marker details">×</button><span className="eyebrow">{selectedPin.mission}</span><h3>{selectedPin.name}</h3><p>{selectedPin.fact}</p><div className="gazetteer-coords">LAT {selectedPin.lat.toFixed(4)}° &nbsp; LON {selectedPin.lon.toFixed(4)}°</div></article></Html>}{selectedSatellite && <Html position={[0, 2.5, 0]} center><article className="satellite-card"><span className="eyebrow">ORBITER LOCKED // NORAD {selectedSatellite.noradId}</span><h3>{selectedSatellite.name}</h3><p>{selectedSatellite.type.toUpperCase()} · ALT {selectedSatellite.alt.toFixed(0)} KM</p><div className="gazetteer-coords">LAT {selectedSatellite.lat.toFixed(3)}° &nbsp; LON {selectedSatellite.lon.toFixed(3)}°</div></article></Html>}</> }

export default function CelestialViewport({ body, onSatelliteSelect }: { body: CelestialBody; onSatelliteSelect?: (satellite: SelectedSatellite) => void }) { const [records, setRecords] = useState<SatelliteRecord[]>([]); const [count, setCount] = useState(0); useEffect(() => { fetch('/api/satellites').then((response) => response.ok ? response.json() : []).then((data: SatelliteRecord[]) => setRecords(data.slice(0, 12000))).catch(() => setRecords([])) }, []); const handleSelect = useCallback((satellite: SelectedSatellite) => onSatelliteSelect?.(satellite), [onSatelliteSelect]); return <div className="orbit-map celestial-canvas" aria-label={`${body} interactive 3D celestial viewport`}><Canvas shadows camera={{ position: [0, 0, 6], fov: 42 }}><color attach="background" args={['#050811']} /><Scene body={body} records={records} onSelect={handleSelect} onReady={setCount} /><OrbitControls enablePan={false} minDistance={3.5} maxDistance={10} enableDamping dampingFactor={0.06} /></Canvas><div className="map-title"><span className="eyebrow">3D CELESTIAL VIEW</span><strong>{body.toUpperCase()} // {count ? `${count.toLocaleString()} ORBITERS` : 'TLE SYNC'}</strong></div><div className="map-legend"><span><i className="legend-dot magenta" />LEO</span><span><i className="legend-dot gold" />MEO</span><span><i className="legend-dot cyan" />GEO</span><span><i className="legend-dot red" />DEBRIS</span></div></div> }
